version: '3.8'

services:
  algorithm:
    build:
      context: ./service
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: service
    volumes:
      - ./service:/app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "8080:8080"

  # db:
  # image: postgres:14
  #   container_name: postgres_container
  #   volumes:
  #     - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   ports:
  #     - "5432:5432"
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    depends_on:
      - algorithm 

    